[project]
name = "voting-app"
description = "A decentralized voting application"
authors = ["Your Name"]
telemetry = true
cache_dir = "./.cache"

[contracts.voting]
path = "contracts/voting.clar"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
